INSERT INTO Product (id, name) VALUES (1, 'Borsodi Sör');
INSERT INTO Product (id, name) VALUES (2, 'Rocky Cellar');
INSERT INTO Product (id, name) VALUES (3, 'Kalinka Vodka');

INSERT INTO CATEGORY (id, name) VALUES (1, 'Sör');
INSERT INTO CATEGORY (id, name) VALUES (2, 'Tömény szeszesital');

INSERT INTO PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_ID) VALUES (1, 1);
INSERT INTO PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_ID) VALUES (2, 1);
INSERT INTO PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_ID) VALUES (3, 2);